import { ConvertOptions } from "xlsx-to-csv-ts";
export const options: ConvertOptions = {
  inputFile: "./public/source/Multiling IOC 14.1.xlsx",
  outputFilename: "Multiling IOC 14.1",
  outputDir: "./public/generated/",
  filter: {
    Order: "order",
    Family: "family",
    "IOC_14.1": "scientific",
    English: "en",
    Catalan: "ca",
    Chinese: "zh-hans",
    "Chinese (Traditional)": "zh-hant",
    Croatian: "hr",
    Czech: "cs",
    Danish: "da",
    Dutch: "nl",
    Finnish: "fi",
    French: "fr",
    German: "de",
    Italian: "it",
    Japanese: "ja",
    Lithuanian: "lt",
    Norwegian: "no",
    Polish: "pl",
    "Portuguese (Lusophone)": "pt-lu",
    "Portuguese (Portuguese)": "pt-pt",
    Russian: "ru",
    Serbian: "sr",
    Slovak: "sk",
    Spanish: "es",
    Swedish: "sv",
    Turkish: "tr",
    Ukrainian: "uk",
    Afrikaans: "af",
    Arabic: "ar",
    Belarusian: "be",
    Bulgarian: "bg",
    Estonian: "et",
    Greek: "el",
    Hebrew: "he",
    Hungarian: "hu",
    Icelandic: "is",
    Indonesian: "in",
    Korean: "ko",
    Latvian: "lv",
    Macedonian: "mk",
    Malayalam: "ms",
    "Northern Sami": "se",
    Persian: "fa",
    Romanian: "ro",
    Slovenian: "sl",
    Thai: "th",
  },
};
